spring:
  application:
    name: DEVSPHERE-USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  data:
    redis:
      password: ${REDIS_PASSWORD:}
