spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  data:
    redis:
      password: ${REDIS_PASSWORD:}

app:
  resume:
    export:
      max-size-bytes: 10485760

