server:
  port: 8761
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: DEVSPHERE-SERVICE-DISCOVERY

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  opentelemetry:
    resource-attributes:
      service.name: devsphere-service-discovery
      service.version: 0.0.1-SNAPSHOT
      deployment.environment: ${SPRING_PROFILES_ACTIVE:development}

