apiVersion: v1
kind: Service
metadata:
  name: devsphere-config-server
  labels:
    app.kubernetes.io/name: devsphere-config-server
    app.kubernetes.io/component: config-server
    app.kubernetes.io/part-of: devsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devsphere-config-server
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
