spring:
  application:
    name: DEVSPHERE-AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

jwt:
  secret: ${JWT_SECRET:devsphere-super-secret-jwt-signing-key-for-local-development-must-be-at-least-256-bits-long}
