apiVersion: v1
kind: Service
metadata:
  name: devsphere-auth-service
  labels:
    app.kubernetes.io/name: devsphere-auth-service
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: devsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devsphere-auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
