apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsphere-api-gateway
  labels:
    app.kubernetes.io/name: devsphere-api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: devsphere
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsphere-auth-service
  labels:
    app.kubernetes.io/name: devsphere-auth-service
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: devsphere
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsphere-user-service
  labels:
    app.kubernetes.io/name: devsphere-user-service
    app.kubernetes.io/component: user-service
    app.kubernetes.io/part-of: devsphere
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsphere-config-server
  labels:
    app.kubernetes.io/name: devsphere-config-server
    app.kubernetes.io/component: config-server
    app.kubernetes.io/part-of: devsphere
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsphere-service-discovery
  labels:
    app.kubernetes.io/name: devsphere-service-discovery
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: devsphere
automountServiceAccountToken: false
