apiVersion: v1
kind: ConfigMap
metadata:
  name: devsphere-configmap
  namespace: devsphere
  labels:
    app.kubernetes.io/name: devsphere-configmap
    app.kubernetes.io/part-of: devsphere
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CONFIG_SERVER_URL: "http://devsphere-config-server.devsphere.svc.cluster.local:8888"
  EUREKA_SERVER_URL: "http://devsphere-service-discovery.devsphere.svc.cluster.local:8761/eureka"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://devsphere-service-discovery.devsphere.svc.cluster.local:8761/eureka/"
  SPRING_REDIS_HOST: "devsphere-redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "devsphere-kafka:9092"
  MYSQL_HOST: "devsphere-mysql"
  MYSQL_PORT: "3306"
  APP_RATE_LIMIT_ENABLED: "true"
  APP_RATE_LIMIT_FAIL_OPEN: "true"
