apiVersion: v1
kind: Secret
metadata:
  name: devsphere-secrets
  namespace: devsphere
  labels:
    app.kubernetes.io/name: devsphere-secrets
    app.kubernetes.io/part-of: devsphere
type: Opaque
stringData:
  SPRING_REDIS_PASSWORD: "CHANGE_ME"
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "CHANGE_ME"
  MYSQL_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_MIN_256_BITS_BASE64_ENCODED_SECRET_KEY"
