apiVersion: v1
kind: Secret
metadata:
  name: devsphere-tls
  namespace: devsphere
  labels:
    app.kubernetes.io/name: devsphere-tls
    app.kubernetes.io/part-of: devsphere
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIID...EXAMPLE_BASE64_CERTIFICATE_DATA...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIE...EXAMPLE_BASE64_PRIVATE_KEY_DATA...
    -----END PRIVATE KEY-----
