apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsphere

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secret.example.yaml
  - infrastructure/mysql.yaml
  - infrastructure/redis.yaml
  - infrastructure/kafka.yaml
  - services/config-server.yaml
  - services/service-discovery.yaml
  - services/api-gateway.yaml
  - services/auth-service.yaml
  - services/user-service.yaml
  - autoscaling/hpa.yaml
  - disruption/pdb.yaml
  - networking/nodeport-gateway.yaml
  - networking/loadbalancer-gateway.yaml
  - ingress/ingress.yaml
  - observability/alerts.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
