apiVersion: v1
kind: Namespace
metadata:
  name: devsphere
  labels:
    app.kubernetes.io/name: devsphere
    app.kubernetes.io/part-of: devsphere
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
