apiVersion: v1
kind: Service
metadata:
  name: nodeport-api-gateway
  namespace: devsphere
  labels:
    app.kubernetes.io/name: nodeport-api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: devsphere
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api-gateway
