server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config-server
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file:${user.dir}/../../config-repo}
          default-label: main
        native:
          search-locations:
            - file:${user.dir}/../../config-repo
            - file:${user.dir}/../config-repo
            - file:${user.dir}/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    probes:
      enabled: true
