apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devsphere
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: user-service
    app.kubernetes.io/part-of: devsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devsphere-user-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
