apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: devsphere
  labels:
    app.kubernetes.io/name: service-discovery
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: devsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devsphere-service-discovery
  ports:
    - name: http
      port: 8761
      targetPort: 8761
