apiVersion: v1
kind: Service
metadata:
  name: devsphere-api-gateway
  labels:
    app.kubernetes.io/name: devsphere-api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: devsphere
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: devsphere-api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
